version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: event_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d eventsdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: event_backend
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/eventsdb?schema=public
      - JWT_SECRET=supersecretproductionkey
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma db push && npm run seed && npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: event_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
